# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
      default: { host: localhost, port: 8000}
    indexes:

          memoiresearch :
               persistence:
                   # the driver can be orm, mongodb or phpcr
                   driver: orm
                   model: App\Entity\Odpf\OdpfFichierspasses
                   provider: ~
                   finder: ~

               properties :
                    nomfichier : ~
                    publie : [value: true]


                
